package org.Exception;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Exception {

	public static void main(String[] args) {
		//ArithMetic Exception
		
		//System.out.println(4/0);
		
		//Null pointer exception
		
//		String str = null;
//		char charAt =str.charAt(2);
//		System.out.println(charAt);
		
		//Stringindexoutofbound
		
//		String str = "java";
//		char charAt = str.charAt(4);
//		System.out.println(charAt);
		//java.lang.StringIndexOutOfBoundsException
		
		
		//java.lang.ArrayIndexOutOfBoundsException
//		int [] a =new int[4];
//		a[0]=10;
//		a[1]=20;
//		a[2]=30;
//		a[3]=40;
//		
//		System.out.println(a[5]);
		 
		//java.lang.IndexOutOfBoundsException
//		List li = new ArrayList();
//		li.add(10);
//		li.add(20);
//		li.add(30);
//		li.add(40);
//		
//		Object object = li.get(6);
//		System.out.println(object);
		
	
		// java.util.InputMismatchException	
//		Scanner s = new Scanner(System.in);
//		System.out.println("Enter the Number :");
//		int nextint = s.nextInt();
//		System.out.println("Entered Number is :"+ nextint);
		
		
	   //java.lang.NumberFormatException
//		String s1 = "java12345";
//		int parseint = Integer.parseInt(s1);
//		System.out.println(parseint);
		
		
	}

}
